name: Sync Silver Folder

on:
  push:
    paths:
      - '**/silver/**' # silver가 포함된 경로의 변화 감지
      - '**/silver/**/**'

jobs:
  sync-silver:
    runs-on: ubuntu-latest

    steps:
      # 1. A 레포지토리 클론
      - name: Checkout A Repository
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          path: A_repo

      # 2. B 레포지토리 클론
      - name: Checkout B Repository
        uses: actions/checkout@v3
        with:
          repository: WeGoEver/HeeChan_Algo
          token: ${{ secrets.TOKEN }} # B 레포지토리에 대한 토큰 필요
          path: B_repo

      # 3. silver 폴더 복사
      - name: Copy Silver Folder to B Repo
        run: |
          mkdir -p B_repo/silver
          cp -r A_repo/**/silver B_repo/ || true

      # 4. B 레포지토리에 커밋 및 푸시

      - name: Commit and Push to B Repository
        run: |
          cd B_repo
          git config user.name "hiki"
          git config user.email "wsx0239@gmail.com"
          
          # 날짜 포맷 (예: 2024-11-23)
          COMMIT_DATE=$(date +'%Y-%m-%d')
          
          git add .
          git commit -m "Sync folder from my repo on $COMMIT_DATE"
          git push
