name: Sync Specific Folders to B Repository

on:
  push:
    branches:
      - main  # main 브랜치 변경 시 트리거

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout A Repository
        uses: actions/checkout@v3

      - name: Filter and Sync to B Repository
        run: |
          # B 레포지토리 클론
          git clone --depth 1 https://<USERNAME>:${{ secrets.TOKEN }}@github.com/<B_REPO_OWNER>/<B_REPO_NAME>.git b-repo
          
          # 필요한 폴더만 복사
          rsync -av --include='silver*/' --include='gold*/' --include='platinum*/' --exclude='*' ./ b-repo/

          # B 레포지토리에 푸시
          cd b-repo
          git add .
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Sync selected folders from A repository"
            git push
          else
            echo "No changes to commit."

